### ISSUE TITLE
Why does this exist?

### ISSUE THREAD

**Issue by balupton** [sindresorhus/sort-keys#8]
When https://www.npmjs.com/package/sortobject did it first?

**Comment by kevva** [comment]
Are you genuinely curious or are you just trying to prove a point (which it feels like since you've opened the exact same issue on multiple repos)?

There are hundreds of duplicate modules in the npm registry, and I'm not saying it's a good thing, but I can see why you'd create a new module to fit your own needs and not having to rely on someone keeping to module updated and accepting PR:s etc. It's just easier having full control yourself.

It can also be as simple as that you don't know that another module exists. In the end I don't think it matters too much, it's no competition. As long as you don't blatantly steals someone else's code without giving proper credit.

**Comment by balupton** [comment]
Actually, that is incorrect too. `detect-indentation` was extracted from https://npmjs.com/package/bal-util which had that functionality before: https://github.com/balupton/bal-util/blob/master/HISTORY.md#v1110-2012-july-1

> Why does https://github.com/bevry/detect-indentation exist when https://github.com/sindresorhus/detect-indent did it first :)?
